name: Website Builder
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/website-builder.yml
      - new/**
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        run: |
          sudo apt install nodejs
      - name: Build website
        run: |
          pwd
          cd new
          npm install
          npm run build
          cd dist
          rm -f ../../deepracer-console-new.zip && zip -r ../../deepracer-console-new.zip .

      - name: Create a draft release
        run: |
          gh release create --draft --prerelease --title $GITHUB_REF --target $GITHUB_REF $GITHUB_REF deepracer-console-new.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Commit updated website
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "Update website archive file" || echo "No changes to commit"
      #     git push
          